# Generated by Django 3.1.2 on 2022-02-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood_app', '0002_auto_20201105_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='name',
            field=models.CharField(choices=[(' Kikuyu ', 'Kikuyu'), ('Dago', 'Dagoretti'), ('Karen', 'Karen'), ('Kabete', 'Kabete'), ('Kasarani', 'Kasarani'), ('Rongai', 'Rongai'), ('Westie', 'Westland'), ('Parkie', 'Parkland'), ('syoki', 'syokimau')], max_length=200),
        ),
    ]
